# Generated by Django 3.2.8 on 2021-11-15 05:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rlcapp', '0003_auto_20211115_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='date_started',
            field=models.DateField(default=datetime.datetime(2021, 11, 15, 5, 7, 57, 478719, tzinfo=utc), verbose_name='Date Started'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='rank',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7')], default='1', max_length=1, null=True),
        ),
    ]
