# Generated by Django 3.2.8 on 2021-11-15 05:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rlcapp', '0004_auto_20211115_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='date_started',
            field=models.DateField(default=datetime.datetime(2021, 11, 15, 5, 11, 44, 720045, tzinfo=utc), verbose_name='Date Started'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='designation',
            field=models.CharField(blank=True, choices=[('Instructor', 'Instructor'), ('Associate Professor', 'Associate Professor'), ('Assistant Professor', 'Assistant Professor'), ('Professor', 'Professor')], default='Instructor', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='rank',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7')], default='1', max_length=1),
        ),
    ]
