# Generated by Django 3.2.8 on 2021-11-15 06:08

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rlcapp', '0005_auto_20211115_1311'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applications',
            options={},
        ),
        migrations.RemoveField(
            model_name='applications',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='applications',
            name='date_completed',
        ),
        migrations.RemoveField(
            model_name='applications',
            name='date_started',
        ),
        migrations.RemoveField(
            model_name='applications',
            name='original_name',
        ),
        migrations.RemoveField(
            model_name='applications',
            name='percent_completed',
        ),
        migrations.RemoveField(
            model_name='applications',
            name='proposal_attachment_file',
        ),
        migrations.RemoveField(
            model_name='applications',
            name='title',
        ),
        migrations.AlterField(
            model_name='faculty',
            name='designation',
            field=models.CharField(choices=[('Instructor', 'Instructor'), ('Associate Professor', 'Associate Professor'), ('Assistant Professor', 'Assistant Professor'), ('Professor', 'Professor')], default='Instructor', max_length=20),
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, verbose_name='Project Name')),
                ('original_name', models.CharField(blank=True, max_length=500, verbose_name='Original Name')),
                ('date_started', models.DateField(default=datetime.datetime(2021, 11, 15, 6, 8, 21, 557810, tzinfo=utc), verbose_name='Date Started')),
                ('date_completed', models.DateField(blank=True, null=True, verbose_name='Date Completed')),
                ('percent_completed', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Percent Completed')),
                ('project_file', models.FileField(blank=True, upload_to='RLC Applications', verbose_name='Project File')),
                ('authors', models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL, verbose_name='Faculty Involved')),
            ],
            options={
                'verbose_name_plural': 'Applications',
                'permissions': [('can_approve_reject', 'Can Approve or Reject RLC')],
            },
        ),
    ]
