# Generated by Django 3.2.8 on 2021-11-15 06:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rlcapp', '0007_auto_20211115_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='date_started',
            field=models.DateField(default=datetime.datetime(2021, 11, 15, 6, 29, 22, 207623, tzinfo=utc), verbose_name='Date Started'),
        ),
    ]
