# Generated by Django 3.2.8 on 2021-11-15 06:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rlcapp', '0008_alter_projects_date_started'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='schoolyear',
            field=models.IntegerField(choices=[(2020, 2020), (2021, 2021), (2022, 2022)], default=2021),
        ),
        migrations.AlterField(
            model_name='projects',
            name='date_started',
            field=models.DateField(default=datetime.datetime(2021, 11, 15, 6, 37, 25, 786902, tzinfo=utc), verbose_name='Date Started'),
        ),
    ]
