# Generated by Django 3.2.8 on 2021-11-16 04:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rlcapp', '0012_auto_20211116_1206'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applications',
            options={'permissions': [('can_approve_reject', 'Can Approve or Reject RLC')], 'verbose_name_plural': 'Applications'},
        ),
        migrations.AlterModelOptions(
            name='progress_reports',
            options={'permissions': [('can_check_progress_reports', 'Can check progress reports')], 'verbose_name_plural': 'Progress Reports'},
        ),
        migrations.AlterModelOptions(
            name='projects',
            options={'permissions': [('can_check_projects', 'Can check projects')], 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterField(
            model_name='progress_reports',
            name='date_submitted',
            field=models.DateField(default=datetime.datetime(2021, 11, 16, 4, 55, 24, 276180, tzinfo=utc), verbose_name='Date Submitted'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='date_started',
            field=models.DateField(default=datetime.datetime(2021, 11, 16, 4, 55, 24, 276180, tzinfo=utc), verbose_name='Date Started'),
        ),
    ]
