# Generated by Django 3.2.8 on 2021-11-16 05:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rlcapp', '0015_auto_20211116_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='applications',
        ),
        migrations.AddField(
            model_name='faculty',
            name='applications',
            field=models.ManyToManyField(blank=True, null=True, to='rlcapp.Applications', verbose_name='Applications'),
        ),
        migrations.AlterField(
            model_name='progress_reports',
            name='date_submitted',
            field=models.DateField(default=datetime.datetime(2021, 11, 16, 5, 27, 9, 632963, tzinfo=utc), verbose_name='Date Submitted'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='date_started',
            field=models.DateField(default=datetime.datetime(2021, 11, 16, 5, 27, 9, 632963, tzinfo=utc), verbose_name='Date Started'),
        ),
    ]
