# Generated by Django 3.2.8 on 2021-11-17 04:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rlcapp', '0018_auto_20211117_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'DRAFT'), ('PENDING APPROVAL', 'PENDING APPROVAL'), ('FOR REVISION', 'FOR REVISION'), ('APPROVED', 'APPROVED'), ('COMPLETED', 'COMPLETED')], default='DRAFT', max_length=30),
        ),
        migrations.AlterField(
            model_name='progress_reports',
            name='date_submitted',
            field=models.DateField(default=datetime.datetime(2021, 11, 17, 4, 0, 29, 823872, tzinfo=utc), verbose_name='Date Submitted'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='date_started',
            field=models.DateField(default=datetime.datetime(2021, 11, 17, 4, 0, 29, 823872, tzinfo=utc), verbose_name='Date Started'),
        ),
    ]
