# Generated by Django 3.2.8 on 2021-11-18 02:08

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rlcapp', '0020_auto_20211117_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='associated_college',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_department': False}, null=True, on_delete=django.db.models.deletion.PROTECT, to='rlcapp.office', verbose_name='College'),
        ),
        migrations.AddField(
            model_name='projects',
            name='associated_department',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_department': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='rlcapp.office', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='progress_reports',
            name='date_submitted',
            field=models.DateField(default=datetime.datetime(2021, 11, 18, 2, 8, 26, 284103, tzinfo=utc), verbose_name='Date Submitted'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='date_started',
            field=models.DateField(default=datetime.datetime(2021, 11, 18, 2, 8, 26, 284103, tzinfo=utc), verbose_name='Date Started'),
        ),
    ]
