# Generated by Django 3.2.8 on 2021-11-24 06:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rlcapp', '0022_auto_20211118_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='prev_status',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='progress_reports',
            name='date_submitted',
            field=models.DateField(default=datetime.datetime(2021, 11, 24, 6, 7, 35, 12499, tzinfo=utc), verbose_name='Date Submitted'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='date_started',
            field=models.DateField(default=datetime.datetime(2021, 11, 24, 6, 7, 35, 12499, tzinfo=utc), verbose_name='Date Started'),
        ),
    ]
