# Generated by Django 3.2.8 on 2021-12-02 04:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rlcapp', '0025_auto_20211202_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress_reports',
            name='date_submitted',
            field=models.DateField(default=datetime.datetime(2021, 12, 2, 4, 43, 5, 859250, tzinfo=utc), verbose_name='Date Submitted'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='date_started',
            field=models.DateField(default=datetime.datetime(2021, 12, 2, 4, 43, 5, 859250, tzinfo=utc), verbose_name='Date Started'),
        ),
    ]
