# Generated by Django 3.2.8 on 2022-03-22 05:14

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rlcapp', '0027_auto_20220322_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='previous_application',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='rlcapp.applications'),
        ),
        migrations.AlterField(
            model_name='progress_reports',
            name='date_submitted',
            field=models.DateField(default=datetime.datetime(2022, 3, 22, 5, 14, 8, 718151, tzinfo=utc), verbose_name='Date Submitted'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='date_started',
            field=models.DateField(default=datetime.datetime(2022, 3, 22, 5, 14, 8, 718151, tzinfo=utc), verbose_name='Date Started'),
        ),
    ]
