# Generated by Django 3.2.8 on 2022-03-31 03:59

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rlcapp', '0032_auto_20220329_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress_reports',
            name='associated_project',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='rlcapp.projects', verbose_name='Associated Project'),
        ),
        migrations.AlterField(
            model_name='progress_reports',
            name='date_submitted',
            field=models.DateField(default=datetime.datetime(2022, 3, 31, 3, 59, 29, 720713, tzinfo=utc), verbose_name='Date Submitted'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rlcapp.applications', verbose_name='Associated Application'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='date_started',
            field=models.DateField(default=datetime.datetime(2022, 3, 31, 3, 59, 29, 705090, tzinfo=utc), verbose_name='Date Started'),
        ),
        migrations.DeleteModel(
            name='Involvement',
        ),
    ]
