# Generated by Django 3.2.8 on 2021-11-11 02:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rlcapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='date_started',
            field=models.DateField(default=datetime.datetime(2021, 11, 11, 2, 33, 10, 941209, tzinfo=utc), verbose_name='Date Started'),
        ),
    ]
