# Generated by Django 3.2.8 on 2021-11-15 06:17

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rlcapp', '0006_auto_20211115_1408'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'permissions': [('can_approve_reject', 'Can Approve or Reject RLC')], 'verbose_name_plural': 'Projects'},
        ),
        migrations.AddField(
            model_name='applications',
            name='projects',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rlcapp.projects'),
        ),
        migrations.AddField(
            model_name='applications',
            name='schoolyear',
            field=models.IntegerField(choices=[(2020, 2020), (2021, 2021)], default=2021),
        ),
        migrations.AddField(
            model_name='applications',
            name='semester_applicable',
            field=models.CharField(choices=[('FIRST', 'FIRST'), ('SECOND', 'SECOND'), ('MIDYEAR', 'MIDYEAR')], default='FIRST', max_length=10),
        ),
        migrations.AddField(
            model_name='applications',
            name='units',
            field=models.CharField(blank=True, max_length=1, verbose_name='Number of Units'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='date_started',
            field=models.DateField(default=datetime.datetime(2021, 11, 15, 6, 17, 23, 240074, tzinfo=utc), verbose_name='Date Started'),
        ),
    ]
