# Generated by Django 3.2.8 on 2021-11-15 06:44

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rlcapp', '0009_auto_20211115_1437'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applications',
            options={'verbose_name_plural': 'Applications'},
        ),
        migrations.AddField(
            model_name='faculty',
            name='applications',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rlcapp.applications', verbose_name='Applications'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='date_started',
            field=models.DateField(default=datetime.datetime(2021, 11, 15, 6, 44, 50, 803883, tzinfo=utc), verbose_name='Date Started'),
        ),
    ]
