# Generated by Django 3.2.8 on 2021-11-16 04:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rlcapp', '0010_auto_20211115_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progress_reports',
            name='accomplishments_file',
        ),
        migrations.RemoveField(
            model_name='progress_reports',
            name='fund_utilization_file',
        ),
        migrations.RemoveField(
            model_name='progress_reports',
            name='problems_and_constraints_file',
        ),
        migrations.RemoveField(
            model_name='progress_reports',
            name='project_id',
        ),
        migrations.AddField(
            model_name='applications',
            name='remarks',
            field=models.TextField(blank=True, default='', verbose_name='Remarks'),
        ),
        migrations.AddField(
            model_name='progress_reports',
            name='date_submitted',
            field=models.DateField(default=datetime.datetime(2021, 11, 16, 4, 1, 40, 462673, tzinfo=utc), verbose_name='Date Submitted'),
        ),
        migrations.AddField(
            model_name='projects',
            name='progress_report',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='rlcapp.progress_reports', verbose_name='Associated Progress Report'),
        ),
        migrations.AddField(
            model_name='projects',
            name='remarks',
            field=models.TextField(blank=True, default='', verbose_name='Remarks'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='projects',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rlcapp.projects', verbose_name='Projects'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='schoolyear',
            field=models.IntegerField(choices=[(2020, 2020), (2021, 2021), (2022, 2022)], default=2021, verbose_name='Schoolyear'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='semester_applicable',
            field=models.CharField(choices=[('FIRST', 'FIRST'), ('SECOND', 'SECOND'), ('MIDYEAR', 'MIDYEAR')], default='FIRST', max_length=10, verbose_name='Applicable Semester'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='date_started',
            field=models.DateField(default=datetime.datetime(2021, 11, 16, 4, 1, 40, 462673, tzinfo=utc), verbose_name='Date Started'),
        ),
        migrations.CreateModel(
            name='Involvement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('involvement', models.CharField(default='', max_length=500, verbose_name='Involvement')),
                ('faculty_id', models.ManyToManyField(default='', to=settings.AUTH_USER_MODEL, verbose_name='Faculty ID')),
                ('project_id', models.ManyToManyField(default='', to='rlcapp.Projects', verbose_name='Project ID')),
            ],
            options={
                'verbose_name_plural': 'Involvement',
            },
        ),
    ]
