# Generated by Django 3.2.8 on 2021-11-16 05:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rlcapp', '0014_auto_20211116_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress_reports',
            name='date_submitted',
            field=models.DateField(default=datetime.datetime(2021, 11, 16, 5, 17, 17, 148533, tzinfo=utc), verbose_name='Date Submitted'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='date_started',
            field=models.DateField(default=datetime.datetime(2021, 11, 16, 5, 17, 17, 148533, tzinfo=utc), verbose_name='Date Started'),
        ),
    ]
