# Generated by Django 3.2.8 on 2021-11-16 05:33

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rlcapp', '0016_auto_20211116_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='progress_report',
        ),
        migrations.AddField(
            model_name='progress_reports',
            name='associated_project',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='rlcapp.projects', verbose_name='Associated Project'),
        ),
        migrations.AlterField(
            model_name='progress_reports',
            name='date_submitted',
            field=models.DateField(default=datetime.datetime(2021, 11, 16, 5, 33, 8, 131569, tzinfo=utc), verbose_name='Date Submitted'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='date_started',
            field=models.DateField(default=datetime.datetime(2021, 11, 16, 5, 33, 8, 131569, tzinfo=utc), verbose_name='Date Started'),
        ),
    ]
