# Generated by Django 3.2.8 on 2022-03-23 06:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rlcapp', '0028_auto_20220322_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress_reports',
            name='date_submitted',
            field=models.DateField(default=datetime.datetime(2022, 3, 23, 6, 6, 15, 397864, tzinfo=utc), verbose_name='Date Submitted'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='date_started',
            field=models.DateField(default=datetime.datetime(2022, 3, 23, 6, 6, 15, 397864, tzinfo=utc), verbose_name='Date Started'),
        ),
    ]
