# Generated by Django 3.2.8 on 2022-03-29 06:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rlcapp', '0030_auto_20220323_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress_reports',
            name='date_submitted',
            field=models.DateField(default=datetime.datetime(2022, 3, 29, 6, 13, 19, 824912, tzinfo=utc), verbose_name='Date Submitted'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='date_started',
            field=models.DateField(default=datetime.datetime(2022, 3, 29, 6, 13, 19, 824912, tzinfo=utc), verbose_name='Date Started'),
        ),
    ]
